version: '3.8'

services:
  cloudnote:
    image: qazzxxx/cloudnote:latest
    container_name: cloudnote
    ports:
      - "6631:3000"
    environment:
      - PASSWORD=123456
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
    restart: unless-stopped
